language: python
python:
    - '2.7'
install:
    - sudo apt-get -qq update 
    - sudo apt-get install -y zip
    - pip install azure-cli
script:
    - ./package.sh
after_success:
    - bash -c "[[ -n \"$TRAVIS_TAG\" ]] && az storage blob upload -f madagascar.zip -n madagascar-${TRAVIS_TAG}.zip -c app || echo 'Skip publishing.'"
    
